default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['DEVELOPMENT_DB_USER']%>
  password: <%= ENV['DEVELOPMENT_DB_PASSWORD']%>
test:
  <<: *default
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['TEST_DB_USER']%>
  password: <%= ENV['TEST_DB_PASSWORD'] %>
production:
  <<: *default
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['PRODUCTION_DB_USER']%>
  password: <%= ENV['PRODUCTION_DB_PASSWORD'] %>
